// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routes

import (
	"github.com/google/wire"
	"golang_framework_echo/controller"
	"golang_framework_echo/repository"
	"golang_framework_echo/service"
)

// Injectors from injector.go:

func InitializePegawaiController() controller.PegawaiController {
	pegawaiRepository := repository.NewPegawaiRepository()
	validate := NewValidator()
	pegawaiService := service.NewPegawaiService(pegawaiRepository, validate)
	pegawaiController := controller.NewPegawaiController(pegawaiService)
	return pegawaiController
}

func InitializeUserController() controller.UserController {
	userRepository := repository.NewUserRepository()
	validate := NewValidator()
	userService := service.NewUserService(userRepository, validate)
	userController := controller.NewUserController(userService)
	return userController
}

// injector.go:

var PegawaiSet = wire.NewSet(repository.NewPegawaiRepository, service.NewPegawaiService, controller.NewPegawaiController)

var UserSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)
